/*
    5. Hello World in Five Languages (Instructions)
---------------------------------------------------------
Write five debug statements that print "Hello World!!!" in five different languages.
*/

System.debug('Hello World!!!');        // English
System.debug('Hola Mundo!!!');         // Spanish
System.debug('Bonjour le Monde!!!');   // French
System.debug('Hallo Welt!!!');         // German
System.debug('Namaste Duniya!!!');     // Hindi
