/*
    3. Missing Line Mystery (Instructions)
------------------------------------------------
Write five debug statements numbered 1 to 5
Comment out one statement (for example, step 3)
Execute the code and check the log
Identify which line is missing and why
*/

System.debug('statement 1');
System.debug('statement 2');
// System.debug('statement 3);
System.debug('statement 4');
System.debug('statement 5');
